<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE people [
    <!ELEMENT people (person*)>
    <!ELEMENT person (name,email,phone+)>
    <!ELEMENT name (firstname,middlename?, lastname)>
    <!ELEMENT firstname (#PCDATA)>
    <!ELEMENT lastname (#PCDATA)>
    <!ELEMENT middlename (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT phone (#PCDATA)>
    <!ATTLIST phone type CDATA "cell|work|fax|home">
]>
<people>
    <person>
        <name>
            <firstname>Jane</firstname>
            <lastname>Doe</lastname>
        </name>
        <email>jdoe@gmail.com</email>
        <phone type="cell">555-555-5555</phone>
        <phone type="work">555-555-5558</phone>
    </person>
    <person>
        <name>
            <firstname>John</firstname>
            <middlename>Q</middlename>
            <lastname>Public</lastname>
        </name>
        <email>jqpublic@gmail.com</email>
        <phone type="cell">555-555-5556</phone>
    </person>
</people>